default_platform(:ios)

platform :ios do
  lane :test do |options|
    scan(
      project: 'DummyProject.xcodeproj',
      scheme: 'DummyProject',
      derived_data_path: '../build/DerivedData',
      device: 'iPhone 8',
      code_coverage: false,
      clean: true,
      cloned_source_packages_path:
        '../build/DerivedData/DummyProject/SourcePackages',
      skip_package_dependencies_resolution: true,
    )
  end
end
