default_platform(:ios)

platform :ios do
  lane :build do |options|
    gym(
      project: 'DummyProject.xcodeproj',
      scheme: 'DummyProject',
      derived_data_path: 'build/DerivedData',
      clean: true,
      configuration: 'Release',
      skip_package_ipa: true,
      skip_archive: true,
      cloned_source_packages_path:
        'build/DerivedData/DummyProject/SourcePackages',
    )
  end
end
